-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, o.sum * p.PRICE AS SALES
FROM (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) as sum
      FROM OFFLINE_SALE
      GROUP BY PRODUCT_ID) o
JOIN PRODUCT p
ON o.PRODUCT_ID = p.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;