-- 코드를 입력하세요
SELECT c.CAR_ID, c.CAR_TYPE, c.DAILY_FEE * 30 * (1 - dp.DISCOUNT_RATE/100) AS FEE
FROM (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단', 'SUV')
    ) c
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
ON c.CAR_TYPE = dp.CAR_TYPE
AND dp.DURATION_TYPE = '30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ch
ON c.CAR_ID = ch.CAR_ID
AND ch.start_date < DATE '2022-12-01'
AND ch.end_date > DATE '2022-11-01'
WHERE ch.car_id IS NULL
AND c.DAILY_FEE * 30 * (1 - dp.DISCOUNT_RATE/100) >= 500000
AND c.DAILY_FEE * 30 * (1 - dp.DISCOUNT_RATE/100) < 2000000
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC;