-- 코드를 입력하세요
SELECT
    EXTRACT(YEAR FROM o.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM o.SALES_DATE) AS MONTH,
    COUNT(DISTINCT o.USER_ID) AS PURCHASED_USERS, 
    ROUND(
        COUNT(DISTINCT o.USER_ID) /
        (SELECT COUNT(*) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'),
        1
    ) AS PUCHASED_RATIO
FROM USER_INFO u
INNER JOIN ONLINE_SALE o
ON u.USER_ID = o.USER_ID
WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
GROUP BY EXTRACT(YEAR FROM o.SALES_DATE), EXTRACT(MONTH FROM o.SALES_DATE)
ORDER BY YEAR, MONTH;