-- 코드를 입력하세요
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, TO_CHAR(r.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE m
INNER JOIN REST_REVIEW r
on m.MEMBER_ID = r.MEMBER_ID
WHERE m.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM (
        SELECT r2.MEMBER_ID, COUNT(r2.MEMBER_ID)
        FROM MEMBER_PROFILE m2
        INNER JOIN REST_REVIEW r2
        on m2.MEMBER_ID = r2.MEMBER_ID
        GROUP BY r2.MEMBER_ID
        ORDER BY 2 DESC
    )
    WHERE ROWNUM <= 1
)
ORDER BY 3 ASC, 2 ASC;