SELECT f1.ITEM_ID, f1.ITEM_NAME, f1.RARITY
FROM ITEM_INFO f1
WHERE f1.ITEM_ID IN (SELECT t1.ITEM_ID FROM ITEM_INFO f2, ITEM_TREE t1 WHERE f2.RARITY = 'RARE' AND f2.ITEM_ID = t1.PARENT_ITEM_ID)
ORDER BY f1.ITEM_ID DESC;