-- 코드를 작성해주세요
-- 분화된 연도별 대장균 크기의 편차 = 분화된 연도별 가장 큰 대장균의 크기 - 각 대장균의 크기

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (MAXSIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA e1
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE)  AS YEAR, MAX(SIZE_OF_COLONY) AS MAXSIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE) 
) e2
ON YEAR(e1.DIFFERENTIATION_DATE) = e2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;