-- 코드를 입력하세요
-- FIRST_HALF 아이스크림 상반기 주문 정보
-- ICECREAM_INFO 아이스크릠 성분 테이블
SELECT f.flavor
FROM FIRST_HALF f JOIN ICECREAM_INFO i
ON f.FLAVOR = i.FLAVOR
WHERE f.TOTAL_ORDER >= 3000 AND i.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;