-- 코드를 작성해주세요
SELECT f1.ID AS ID, f2.FISH_NAME AS FISH_NAME, f1.LENGTH AS LENGTH
FROM FISH_INFO f1 join FISH_NAME_INFO f2
ON f1.FISH_TYPE = f2.FISH_TYPE
WHERE ( f1.FISH_TYPE, f1.LENGTH) IN (
            SELECT FISH_TYPE, MAX(LENGTH)
            FROM FISH_INFO
            GROUP BY FISH_TYPE
)
ORDER BY f1.ID ASC;